#!/usr/bin/env bash

export PS4='+${BASH_SOURCE}:${LINENO}:${FUNCNAME[0]:+${FUNCNAME[0]}():} '

set -e
set -u
set -o pipefail

readonly progname="${0##*/}"

function print-help() {
    cat <<EOH
Usage: $progname [OPTIONS] [-- ARGUMENTS]
Checks code coverage and optionally opens the report.

OPTIONS:
  -h, --help            print this help and exit
  -m, --with-mutation   also check mutation coverage
  -o, --open-report     open coverage reports in a web browser
  -x, --no-rerun        only open coverage reports, do not rerun build

ARGUMENTS:
  All arguments are passed to ./mvnw as options.  The "--" is mandatory.
EOH
}

function bad-option() {
    local opt="$1"

    cat <<EOM
$progname: invalid option -- '$opt'
Try '$progname --help' for more information.
EOM
}

function require-file() {
    local file="$1"
    shift
    if [[ ! -f "$file" ]]; then
        echo "$progname: $file: No such file or directory" >&2
        exit 1
    fi
}

mutation=false
open=false
run=true
# shellcheck disable=SC2214
while getopts :hmox-: opt; do
    [[ $opt == - ]] && opt=${OPTARG%%=*} OPTARG=${OPTARG#*=}
    case $opt in
    h | help)
        print-help
        exit 0
        ;;
    m | with-mutation) mutation=true ;;
    o | open-report) open=true ;;
    x | no-rerun) open=true run=false ;;
    *)
        bad-option "$OPTARG"
        exit 2
        ;;
    esac
done
shift $((OPTIND - 1))

if $run; then
    if $mutation; then
        targets='clean verify'
    else
        targets='clean test jacoco:report jacoco:check'
    fi

    # shellcheck disable=SC2086
    ./mvnw "$@" $targets
fi

for file in target/jacoco.exec target/site/jacoco/index.html; do
    require-file "$file"
done
if $mutation; then
    require-file target/pit-reports/index.html
fi

if $open; then
    (cd target/site/jacoco && open index.html)
    if $mutation; then
        (cd target/pit-reports && open index.html)
    fi
fi
