#!/usr/bin/env bash

export PS4='+${BASH_SOURCE}:${LINENO}:${FUNCNAME[0]:+${FUNCNAME[0]}():} '

set -e
set -u
set -o pipefail

readonly progname="${0##*/}"

function print-help() {
    cat <<EOH
Usage: $progname [OPTIONS] [-- ARGUMENTS]
Checks code coverage and optionally opens the report.

OPTIONS:
  -f, --full-coverage   check with 100% coverage to find failures
  -h, --help            print this help and exit
  -m, --with-mutation   also check mutation coverage
  -o, --open-report     open coverage reports in a web browser
  -x, --no-rerun        only open coverage reports, do not rerun build

ARGUMENTS:
  All arguments are passed to ./mvnw as options.  The "--" is mandatory.
EOH
}

function bad-option() {
    local opt="$1"

    cat <<EOM
$progname: invalid option -- '$opt'
Try '$progname --help' for more information.
EOM
}

function require-file() {
    local file="$1"
    shift
    if [[ ! -f "$file" ]]; then
        echo "$progname: $file: No such file or directory" >&2
        return 1
    fi
}

full=false
mutation=false
open=false
run=true
# shellcheck disable=SC2214
while getopts :fhmox-: opt; do
    [[ $opt == - ]] && opt=${OPTARG%%=*} OPTARG=${OPTARG#*=}
    case $opt in
    f | full-coverage) full=true ;;
    h | help)
        print-help
        exit 0
        ;;
    m | with-mutation) mutation=true ;;
    o | open-report) open=true ;;
    x | no-rerun) open=true run=false ;;
    *)
        bad-option "$OPTARG"
        exit 2
        ;;
    esac
done
shift $((OPTIND - 1))

if $full; then
    flags='-Dcoverage.lines=100 -Dcoverage.branches=100 -Dcoverage.instructions=100 -Dcoverage.mutation=100'
else
    flags=''
fi

((rc = 0)) || true
if $run; then
    if $mutation; then
        targets='-DwithHistory clean verify'
    else
        targets='clean test jacoco:report jacoco:check'
    fi

    # shellcheck disable=SC2086
    ./mvnw $flags "$@" $targets || ((rc += $?)) || true
else
    # Refresh coverage report when editing limits in pom.xml without rebuild
    ./mvnw $flags "$@" jacoco:report jacoco:check || ((rc += $?)) || true
fi

if $open; then
    if require-file target/site/jacoco/index.html; then
        (cd target/site/jacoco && open index.html)
    else
        ((++rc))
    fi
    if $mutation && require-file target/pit-reports/index.html; then
        (cd target/pit-reports && open index.html)
    else
        ((++rc))
    fi
fi

# shellcheck disable=SC2086
exit $rc
